--SELECT DISTINCT replacement_cost from film;
--SELECT COUNT(DISTINCT replacement_cost) from film;
--SELECT COUNT(title) from film where title LIKE 'T%' and rating='G';
--SELECT COUNT(country) from country where country LIKE '_____';
--SELECT COUNT(city) from city where city ILIKE '%R';
