--select country from country where country LIKE 'A%a';
--select country from country where country LIKE '_____n';
--select title from film where title ILIKE '%T%T%T%T%';
--select title, rental_rate, length from film where title LIKE 'C%'and (rental_rate='2.99' and length>90);
